[package]
name = "formdata"
version = "0.7.0"
description = "Parsing of multipart/form-data"
authors = [
        "Mike Dilger <mike@optcomp.nz>",
        "Skyler Lipthay <skyler.lipthay@gmail.com>",
        ]
readme = "README.md"
repository = "https://github.com/mikedilger/formdata"
documentation = "https://mikedilger.github.io/formdata"
license = "MIT"
keywords = ["multipart", "form-data", "hyper", "http", "mime"]

[dependencies]
hyper = "^0.6"
httparse = "^0.1"
mime = "*"
libc = "*"
tempdir = "*"
textnonce = "*"
log = "*"
