[package]
name = "formdata"
version = "0.3.0"
description = "Parsing of multipart/form-data"
authors = [ "Mike Dilger <mike@efx.co.nz>"  ]
readme = "README.md"
repository = "https://github.com/mikedilger/formdata"
license = "MIT"
keywords = ["multipart", "form-data"]

[dependencies]
hyper = "*"
httparse = "*"
mime = "*"
libc = "*"
tempdir = "*"
textnonce = "*"
