[package]
name = "formdata"
version = "0.1.0"
description = "Parsing of multipart/form-data"
authors = [ "Mike Dilger <mike@efx.co.nz>" ]
readme = "README.md"
repository = "https://github.com/mikedilger/formdata"
license = "MIT"
keywords = ["multipart", "form-data"]

[dependencies]
hyper = "0.5.2"
httparse = "*"
mime = "0.0.11"
libc = "*"
tempdir = "*"
textnonce = "*"